### ISSUE TITLE
Output dir error: The directory name is invalid

### ISSUE THREAD

**Issue by pjhavariotis** [aws-samples/aws-auto-inventory#52]
- Version: Latest
- Local OS Version: Windows 10 22H2
- Local chip architecture: <x86>
- Reproduces in: <environment, AWS Account ID>

Steps to Reproduce:
I have utilised the 
1.`.\aws-auto-inventory-windows.exe -s .\services\running_ec2.json --output_dir c:\Apps\aws-auto-inventory\output\`
2.I'm getting the following output:
```
ERROR:__main__:'us-east-1' generated an exception: [WinError 267] The directory name is invalid: 'c:\\Apps\\aws-auto-inventory\\output\\2023-08-25T11:08'
ERROR:__main__:Traceback (most recent call last):
  File "scan.py", line 317, in main
  File "os.py", line 215, in makedirs
  File "os.py", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\\Apps\\aws-auto-inventory\\output\\2023-08-25T11:08'

Total elapsed time for scanning: 0h:0m:2s

```

**Comment by pjhavariotis** [comment]
BTW, If I neglect to put the `output_dir` argument, I'm getting the following error:
```
ERROR:__main__:'us-east-1' generated an exception: [WinError 267] The directory name is invalid: 'output\\2023-08-25T11:16'
ERROR:__main__:Traceback (most recent call last):
  File "scan.py", line 317, in main
  File "os.py", line 215, in makedirs
  File "os.py", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'output\\2023-08-25T11:16'

Total elapsed time for scanning: 0h:0m:1s
```

**Comment by valter-silva-au** [comment]
@pjhavariotis please try with the new version.

**Comment by pjhavariotis** [comment]
The latest release is still 1.1.0. I will try it as soon as the new release is out.
